matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "9"
      script: cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint
    - language: android
      os: linux
      env:
        - WebPack="Android"
      jdk: oraclejdk8
      before_install:
        - nvm install 9
        - yes | sdkmanager "platforms;android-27"
      script: cd demo && npm run build.plugin && npm i && tns build android --bundle --env.uglify --env.snapshot
    - language: android
      env:
        - BuildAndroid="27"
      os: linux
      jdk: oraclejdk8
      before_install:
        - nvm install stable
        - yes | sdkmanager "platforms;android-27"
      script:
        - cd src && npm i && npm run tsc && cd ../demo && tns build android
    - os: linux
      language: android
      dist: precise
      sudo: required
      jdk: oraclejdk8
      before_script:
        - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
      before_install:
        - nvm install 6
        - yes | sdkmanager "platforms;android-27"
      script: cd src && npm run test.android

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - android-23
    - extra-android-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-android-21

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
